version: '2.2'

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "8080:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

  backend:
    image: mysql:5.7
    container_name: backend
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - backend_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    # command: | 
    #   CREATE TABLE IF NOT EXISTS mytable (
    #       id INT AUTO_INCREMENT PRIMARY KEY,
    #       data VARCHAR(255) NOT NULL
    #   );
    
    #   INSERT INTO mytable (data) VALUES ('Data 1'), ('Data 2'), ('Data 3');


  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/var/www/html
    depends_on:
      - backend

volumes:
  backend_data:
